### ISSUE TITLE
Programm panics, when passed file is empty (size 0 bytes)

### ISSUE THREAD

**Issue by timoknapp** [go-flac/go-flac#1]
https://github.com/go-flac/go-flac/blob/master/util.go#L101

in util.go there are still some panic statement. It would recommend to always pass through the errors or otherwise check whether the files are not empty.

**Comment by timoknapp** [comment]
Done

**Comment by timoknapp** [comment]
@eternal-flame-AD will you also release a new version soon?

**Comment by eternal-flame-AD** [comment]
Yeah, I am taking another review in this repo and I might finish up this weekend.

**Comment by timoknapp** [comment]
Great thanks
