### ISSUE TITLE
How to set a flac artist, album, etc.

### ISSUE THREAD

**Issue by heyitscassio** [go-flac/go-flac#3]
Hello, I'm making a program and need to tag a flac file with te correct artist name. But I didn't find a clear way using this lib, there is any way of doing that?

**Comment by Sorrow446** [comment]
If you're still interested. This won't overwrite. If you want code to wipe tags, let me know.
```go
func writeTags(trackPath string) error {
	f, err := flac.ParseFile(trackPath)
	if err != nil {
		return err
	}
	tag := flacvorbis.New()
	tag.Add("ARTIST", "albumHere")
	tagMeta := tag.Marshal()
	f.Meta = append(f.Meta, &tagMeta)
	err = f.Save(trackPath)
	return nil
}
```

**Comment by heyitscassio** [comment]
Thanks! I found a way of doing that using https://github.com/go-flac/flacvorbis
