### ISSUE TITLE
Remove dependency to http-client

### ISSUE THREAD

**Issue by vmichalak** [go-flac/go-flac#4]
https://github.com/go-flac/go-flac/blob/c25677a9a510533e97ce42c0d770d750e037743d/flac_test.go#L8

The dependency to http-client is only needed for unit testing. Maybe removing it would be a good idea for long time ?

**Comment by eternal-flame-AD** [comment]
Thanks! I will remove th need of a third party http library completely.

This package was made when I was still learning go and have a use for it, looks like there is more popularity to it than I expected, there are a few changes I will make
