### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by chaunsin** [go-flac/go-flac#5]
hello! 
When I was using this library, I found that the operation storage occupation was too high. I was dealing with a very large music file, with a size of 1GB. I consulted the code and found that the method used was to read the entire file content and put it into the memory, the code is as follows:

https://github.com/go-flac/go-flac/blob/f00c9b269384bc0a20b1093e76827b6b0a9b802a/util.go#L33
``` go
func readFLACStream(f io.Reader) ([]byte, error) {
	result, err := ioutil.ReadAll(f)
	if err != nil {
		return nil, err
	}
	if result[0] != 0xFF || result[1]>>2 != 0x3E {
		return nil, ErrorNoSyncCode
	}
	return result, nil
}
```
I think the improvement method is to use the io.ReadSeeker interface for file management and modify the original content instead of loading it all into memory for data modification management or using the buffer mode。

Hope to optimize this problem, thank you very much!!

**Comment by eternal-flame-AD** [comment]
@chaunsin  Thanks, when I wrote this library my purpose was to manipulate rips of my CDs where this shouldn't be a problem. This should be optimized. Would you like to do a PR? If not I will push a fix probably on Thursday or Friday.

**Comment by chaunsin** [comment]
> @chaunsin Thanks, when I wrote this library my purpose was to manipulate rips of my CDs where this shouldn't be a problem. This should be optimized. Would you like to do a PR? If not I will push a fix probably on Thursday or Friday.

Thanks for reply！ no spare time at the moment。

**Comment by eternal-flame-AD** [comment]
No worries, will push a fix by the end of this week at the latest.

**Comment by eternal-flame-AD** [comment]
@chaunsin I pushed a new major version because of the API change. You might need to update your `go.mod` file.

**Comment by chaunsin** [comment]
> @chaunsin I pushed a new major version because of the API change. You might need to update your `go.mod` file.

Ok, I'll try. Thank you

**Comment by chaunsin** [comment]
> @chaunsin I pushed a new major version because of the API change. You might need to update your `go.mod` file.

The following error occurred:

`Cannot use '*block' (type "github.com/go-flac/go-flac/v2".MetaDataBlock) as the type "github.com/go-flac/go-flac".MetaDataBlock`

github.com/go-flac/flacvorbis need to update dependency。

https://github.com/go-flac/flacvorbis/blob/a593e7217fa2ec5e93b74902a714f836901ca7cc/vorbis.go#L66

**Comment by eternal-flame-AD** [comment]
@chaunsin  I will open a new issue on the other repos to use the new blocks

**Comment by eternal-flame-AD** [comment]
@chaunsin It should work now, just update all the dependencies to the `/v2` suffix!

**Comment by chaunsin** [comment]
> @chaunsin It should work now, just update all the dependencies to the `/v2` suffix!

ok i will try tks!

**Comment by chaunsin** [comment]
> @chaunsin It should work now, just update all the dependencies to the `/v2` suffix!

That looks fine for now. Thank you！！！
