### ISSUE TITLE
Close() method still leaves the Flac file open

### ISSUE THREAD

**Issue by echoxxzz** [go-flac/go-flac#8]
This does not work:

f, _ := flac.ParseFile(`test.flac`)
f.Close()
fmt.Println(os.Remove(`test.flac`))

The file is still open.

**Comment by eternal-flame-AD** [comment]
Thanks for the report, I know where the issue was, will push a fix this week.

**Comment by echoxxzz** [comment]
Many thanks.

**Comment by eternal-flame-AD** [comment]
fixed in abdbba28ab2813b587dfd2395d8d67155e6c9764, pushed v2.0.3 tag.
